### ISSUE TITLE
Can't turn the options on again

### ISSUE THREAD

**Issue by silviasfon** [meooow25/carrot#30]
I turned off all the options during  a contest and now I can't turn them on again, since they don't appear. I tried removing and installing the extension again but it didn't work.
![image](https://user-images.githubusercontent.com/49081447/100636728-c440b380-3310-11eb-912e-b5cb7d255847.png)

**Comment by meooow25** [comment]
I'm not able to reproduce this. Would be great if you could share more details on how to do that, if possible.

Note that it might take a while for the options to appear, because they show up after the data is fetched and calculated. Does it not show up even after some seconds (or minutes if the connection is really slow)?
Also, please share if you can see any message from the extension in the browser console.

**Comment by meooow25** [comment]
> I'm not sure if it was the cause of the issue, but during one round I turned off all the three display options.

Probably not, but please reopen if it happens again.
