### ISSUE TITLE
Didn't show final rating changes

### ISSUE THREAD

**Issue by TrendBattles** [meooow25/carrot#42]
![image](https://user-images.githubusercontent.com/70185198/185791350-a2fbf538-2875-48d8-b820-4e13ddd1a134.png)
I tried to reload for several minutes just to make sure if it wasn't working and yes, this was what looked like after that.

**Comment by meooow25** [comment]
Hello, thanks for reporting. The Codeforces API is currently down, which is why the extension is unable to get data and show rating changes. Going to something like https://codeforces.com/api/contest.list shows the message "The page is temporarily blocked by administrator."  
The API is outside my control, but I can try to add better messaging about the cause of failure.
