### ISSUE TITLE
Error: CF API: HTTP error 404: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"> <html> <head> <meta http-equiv…

### ISSUE THREAD

**Issue by mohabmohamed44** [meooow25/carrot#55]
the error is here and the extension is not working any more 
console.error('[Carrot] Predict error: %o', er);

fix please

**Comment by meooow25** [comment]
Thanks for reporting. I can see this error on visiting any contest standings page.

The reason seems to be that the Codeforces server is returning a 404 error on all API end points.

![image](https://github.com/meooow25/carrot/assets/13716304/91705693-c9ac-453a-b28a-f7bbc84e0e80)

Since this is a problem with the Codeforces server, unfortunately I cannot do anything about it 😞 
We have to wait until someone at Codeforces decides to enable the API again.

**Comment by meooow25** [comment]
I believe the API is working again now.

**Comment by mohabmohamed44** [comment]
Thanks for your reply
