### ISSUE TITLE
NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by EricLindesay** [meooow25/carrot#64]
In v0.6.6 (most recent available on Firefox), I get `Error: NetworkError when attempting to fetch resource`. 
The error is in `content.js:371:17` and is `Predict Error: Error: NetworkError when attempting to fetch resource`. I have no clue what causes it. It has been an issue for a few weeks now.
All permissions it requests are enabled.

**Comment by meooow25** [comment]
Thanks for reporting. I see this in network requests

![cf240921](https://github.com/user-attachments/assets/897d1ad9-8bf8-4a44-84a0-6dd4e4f3ae78)

So Codeforces wanted to serve a 403 (known issue) but this time did not even set the right headers.

The 403 issue has been reported before (#56, etc) and might be fixed by #61.
